language: rust
sudo: false
cache: cargo
rust:
  - stable
env:
  global:
    - PKG_CONFIG_ALLOW_CROSS=1
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - libssl-dev:i386
      - gcc-multilib
# Install the components for 32 bit cross-compiling
before_install:
  - rustup target add i686-unknown-linux-gnu
install:
  - cargo build --verbose --target i686-unknown-linux-gnu
script:
  - cargo test --verbose --target i686-unknown-linux-gnu
